### ISSUE TITLE
An exception in Driver.cpp in set_option function in line 763

### ISSUE THREAD

**Issue by bahruzjabiyev** [vlab-cs-ucsb/ABC#8]
Hey there.

Thank you for building such a product and putting it out for the public use.

I am trying to use ABC with SPF (Symbolic Pathfinder). It is a symbolic execution engine based on JPF (Java Pathfinder).

When I run it, I get this exception I don't sadly know how to fix:
`E0106 12:59:33.718792 23095 Driver.cpp:763] option is not recognized: 0 -> ./`

For the full context of the exception please visit [here](https://pastebin.com/CF5wA6EF).

Any ideas why it is happening or possibly how to fix this?

**Comment by william-eiers** [comment]
Thank you for checking out ABC!

The exception in question is thrown when an invalid parameter is given to ABC, often due to a misconfiguration. I've used SPF with ABC and haven't experienced this particular error. Which version of SPF are you using? The one from https://github.com/SymbolicPathFinder/jpf-symbc?

The JPF file you uses was "src/examples/strings/TestMain.jpf". I didn't see that in the main SPF repository. Would you mind sending it to me so I can replicate the issue?

**Comment by bahruzjabiyev** [comment]
Thank you, William, for taking the time to reply to my question.

Yes, I am using the same system. I have followed the download instructions in the [README](https://github.com/SymbolicPathFinder/jpf-symbc/blob/master/README.md) of the repo.

TestMain.jpf is my own code. Can you please use [GoodbyeWorld.jpf](https://github.com/SymbolicPathFinder/jpf-symbc/blob/master/src/examples/strings/GoodbyeWorld.jpf) to replicate the issue? Only change that you have to make in GoodbyeWorld.jpf is to change `symbolic.string_dp=z3str2` to `symbolic.string_dp=ABC`.

**Comment by william-eiers** [comment]
Looks like that specific commit of SPF contains an out-of-date translator from SPF string path conditions to SMT2 string constraints. The most recent branch of SPF has the latest version, but if you want to use that particular commit then it's a pretty simple fix.

In the file jpf-symbc/src/main/gov/nasa/jpf/symbc/string/translate/TranslateToABC.java, comment out the lines 23-25:
abcDriver.setOption(Option.OUTPUT_PATH, "./");
abcDriver.setOption(Option.LIA_ENGINE_ENABLED, true);
abcDriver.setOption(Option.MODEL_COUNTER_ENABLED, true);

After that, rebuild SPF and try again. It should run fine this time, but let me know if you still run into any problems!

**Comment by bahruzjabiyev** [comment]
Thank you, William, for your time and help. 

Using the latest SPF (not a particular commit) solved the issue.
